import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabaseClient'
import { createSubtasks, getSubtasks } from '../lib/api'
import DuckSVG from '../components/DuckSVG'

export default function BreakdownPage() {
  const { taskId } = useParams()
  const navigate = useNavigate()
  const [task, setTask] = useState(null)
  const [subtasks, setSubtasks] = useState([])
  const [steps, setSteps] = useState(['', '', ''])
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    async function load() {
      const { data } = await supabase.from('tasks').select('*').eq('id', taskId).single()
      setTask(data)
      setSubtasks(await getSubtasks(taskId))
    }
    load()
  }, [taskId])

  async function handleSave() {
    setSaving(true)
    const created = await createSubtasks(task, steps)
    setSubtasks((prev) => [...prev, ...created])
    setSteps(['', '', ''])
    setSaving(false)
  }

  if (!task) return <div className="p-6 text-sm text-textMuted">Loading…</div>

  return (
    <div className="p-4">
      <button onClick={() => navigate(-1)} className="mb-3 text-lg font-bold">
        ← Breaking it down
      </button>

      <div className="mb-3 flex items-end gap-2">
        <DuckSVG width={56} height={70} />
        <div className="flex-1 rounded-wobble border-2 border-border bg-white p-3 text-sm font-semibold">
          {task.title} — pick one small step:
        </div>
      </div>

      {subtasks.length > 0 && (
        <div className="mb-3 flex flex-col gap-2">
          {subtasks.map((s) => (
            <div key={s.id} className="rounded-wobble border-2 border-border bg-white p-3 text-sm font-semibold">
              {s.title}
            </div>
          ))}
        </div>
      )}

      <div className="flex flex-col gap-2">
        {steps.map((value, i) => (
          <input
            key={i}
            value={value}
            onChange={(e) => {
              const next = [...steps]
              next[i] = e.target.value
              setSteps(next)
            }}
            placeholder={`Small step ${i + 1} (e.g. open the document)`}
            className="rounded-2xl border-2 border-border px-3 py-2 text-sm"
          />
        ))}
      </div>

      <button
        onClick={handleSave}
        disabled={saving}
        className="mt-3 w-full rounded-wobble bg-leaf py-3 text-base font-bold text-leafText disabled:opacity-60"
      >
        Save smallest steps
      </button>

      <p className="mt-2 text-center text-xs text-textMuted">
        No guilt — any step counts. (Later this gets auto-generated by Claude via FastAPI.)
      </p>
    </div>
  )
}
